#!/bin/sh

set -e

case "$1" in
    remove|upgrade|deconfigure)
        if [ -d /run/systemd/system ]; then
            systemctl stop openhd-sys-utils.service >/dev/null 2>&1 || true
        fi
        ;;
esac

exit 0
