name: Build & Release
on: 
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Build
        run: |
          ls -a
          mkdir -p openhd_sys_utils/usr/local/bin
          chmod +x *.sh
          mv *.sh openhd_sys_utils/usr/local/bin
          mkdir -p openhd_sys_utils/etc/system/systemd/
          mv *.service openhd_sys_utils/etc/system/systemd/
          sudo gem install fpm
          fpm -a armhf -s dir -t deb -n openhd_sys_utils -v 0.1 -C openhd_sys_utils -p openhd_sys_utils_VERSION_ARCH.deb
          fpm -a arm64 -s dir -t deb -n openhd_sys_utils -v 0.1 -C openhd_sys_utils -p openhd_sys_utils_VERSION_ARCH.deb

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: |
            *.deb
      - name: Push
        id: push
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "deb"
          owner: "openhd"
          repo: "release"
          distro: "any-distro"
          release: "any-version"
          republish: "true" # needed ONLY if version is not changing
          file: "*.deb"